[package]
name = "nbtsniper"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.3"
flate2 = "1.0.34"
thiserror = "1.0.64"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"